### ISSUE TITLE
Unable to activate Unity

### ISSUE THREAD

**Issue by bssughosh** [kuler90/activate-unity#7]
After the alf file is created, It is stuck in `License robot. Login...`

```
Unity Editor version:    2020.3.33f1 (915a7af8b0d5)
Branch:                  2020.3/staging
Build type:              Release
Batch mode:              YES
System name:             Linux
Distro version:          #25~20.04.1-Ubuntu SMP Thu Sep 1 19:20:56 UTC 2022
Kernel version:          5.15.0-1020-azure
Architecture:            x86_64
Available memory:        6944 MB
[LicensingClient] Channel doesn't exist: "LicenseClient-runner"
[Licensing::Module] Successfully launched the LicensingClient (PId: 4045)
[SignatureVerifier] Application signature verification not supported on this platform.
[Licensing::Module] Successfully connected to LicensingClient on channel: "LicenseClient-runner" (connect: 1.09s, validation: 0.11s, handshake: 0.00s)
[Licensing::Module] Connected to LicensingClient (PId: 4045, launch time: 0.00, total connection time: 1.19s)
Entitlement-based licensing initiated
[LicensingClient] Licenses updated successfully
[Licensing::Module] Error: License is not active (com.unity.editor.headless). HasEntitlements will fail.
Pro License: NO

 Generating manual activation license file.

LICENSE SYSTEM [2022927 13:12:18] License activate file written to: Unity_v2020.3.33f1.alf

 Manual activation license file saved.
License robot. Start
License robot. Login...
TimeoutError: Navigation timeout of 120000 ms exceeded
    at /home/runner/work/_actions/kuler90/activate-unity/v1/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:108:111
    at async FrameManager.waitForFrameNavigation (/home/runner/work/_actions/kuler90/activate-unity/v1/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:168:23)
    at async Frame.waitForNavigation (/home/runner/work/_actions/kuler90/activate-unity/v1/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:5[36](https://github.com/****/myracle-andromeda/actions/runs/3135801316/jobs/5091916067#step:4:37):16)
    at async Page.waitForNavigation (/home/runner/work/_actions/kuler90/activate-unity/v1/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1229:16)
    at async Promise.all (index 1)
    at async licensePage_login (/home/runner/work/_actions/kuler90/activate-unity/v1/src/license-robot.js:49:5)
    at async browser_getPersonalLicense (/home/runner/work/_actions/kuler90/activate-unity/v1/src/license-robot.js:23:9)
    at async retry (/home/runner/work/_actions/kuler90/activate-unity/v1/src/license-robot.js:1[40](https://github.com/****/myracle-andromeda/actions/runs/3135801316/jobs/5091916067#step:4:41):20)
    at async Object.getPersonalLicense (/home/runner/work/_actions/kuler90/activate-unity/v1/src/license-robot.js:12:25)
    at async run (/home/runner/work/_actions/kuler90/activate-unity/v1/src/activate-license.js:23:33)
License robot. Login...
```

**Comment by RubberDuckShobe** [comment]
Judging by the issue being closed, you've fixed it? How did you do that?
